name: validate docker-compose.yml

on:
  push:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/validate-compose.yml'
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/validate-compose.yml'

jobs:
  validate-compose:
    name: validate docker-compose.yml
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: validate
        run: |
          docker compose -f docker-compose.yml config

